### ISSUE TITLE
Parsing is not expecting quote-enclosed values

### ISSUE THREAD

**Issue by Teun** [nsc-c-park/mssql-connection-string#3]
Both keys and values in connection strings can be enclosed in single or double quotes. That way, they can start with spaces, contain semicolons and equal signs, etc.

The current parsing logic, with string splitting, is very naive and can only work for very simple formats. Connection strings are not that simple. An interesting summary of the format is to be [found here](https://www.connectionstrings.com/formating-rules-for-connection-strings/).

Parsing non-trivial formats should not be done by string-splitting and indexing, nor using regexes. I will create a pull request with unit tests that show the problems and an implementation using a generated parser using [pegjs](https://pegjs.org/).

**Comment by jczas** [comment]
merged and published to npm as 0.1.0
